version: '3.7'

# from https://github.com/zeebe-io/zeebe-simple-monitor/

services: 
  zeebe:
    container_name: zeebe
    build:
     context: ./zeebe
    environment:
        - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "5701:5701"

  monitor:
    container_name: monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
        - zeebe

  app:
    container_name: app
    build:
      context: ./axon-zeebe-app
    environment:
      - ZEEBE_BROKER_HOST=zeebe
    ports:
      - "8081:8081"
    depends_on:
        - zeebe
