version: '3.7'

# from https://github.com/zeebe-io/zeebe-simple-monitor/

services: 
  zeebe:
    container_name: zeebe
    build:
     context: ./zeebe
    environment:
        - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "5701:5701"
#    volumes:
#      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml

#  zeebe:
#    image: camunda/zeebe-with-hazelcast-exporter:latest
#    container_name: zeebe
#    ports:
#      - "26500:26500"
#      - "5701:5701"
#    volumes:
#      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml

  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8080:8080"
    depends_on:
        - zeebe

#  app:
#    container_name: app
#    build:
#      context: ./axon-zeebe-app
#    environment:
#      - ZEEBE_BROKER_HOST=zeebe
#    ports:
#      - "8081:8081"
#    depends_on:
#        - zeebe
