FROM camunda/zeebe-with-hazelcast-exporter:latest

#RUN cp /usr/local/zeebe/exporters/zeebe-hazelcast-exporter-jar-with-dependencies.jar /usr/local/zeebe/lib

#COPY ./zeebe.cfg.toml /usr/local/zeebe/conf/
COPY ./application.yaml /usr/local/zeebe/config/